### ISSUE TITLE
add a support for groq

### ISSUE THREAD

**Issue by meetkool** [TransformerOptimus/SuperCoder#93]
add a support for groq https://console.groq.com/ as ppl some time don't want to use openai keys just some FOSS models this method can be a starting point 
then u can all go through the olama or vllm intrigation in this

**Comment by mattlgroff** [comment]
Groq supports OpenAI Compatibility https://console.groq.com/docs/openai

It might speed up support to take advantage of this.

**Comment by neelayan7** [comment]
Hey.
So we tried a bunch of FOSS Models with SuperCoder, but the results honestly weren't that great and that's why we didn't implement it. Coding capabilities were great, but planning and other modules weren't really good.
We're currently testing with Llama 405b, hopefully that works well and we'll add that support.

**Comment by meetkool** [comment]
@neelayan7 
oh thats amazing

**Comment by luciferlinx101** [comment]
Closing the issue as it seems resolved!
